/** 与后端 ErrorCodes 对齐的前端错误码副本。 */
export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  AUTH_INVALID: "AUTH_INVALID",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  ORDER_DUPLICATE_REQUEST: "ORDER_DUPLICATE_REQUEST",
  IDEMPOTENT_CONFLICT: "IDEMPOTENT_CONFLICT",
  ILLEGAL_STATUS_TRANSITION: "ILLEGAL_STATUS_TRANSITION",
  BATCH_NOT_FOUND: "BATCH_NOT_FOUND",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  BATCH_CONTENDED: "BATCH_CONTENDED",
  WAREHOUSE_MISMATCH: "WAREHOUSE_MISMATCH",
  LINE_EMPTY: "LINE_EMPTY",
  ALLOCATION_MISSING: "ALLOCATION_MISSING",
  LEDGER_IMBALANCE: "LEDGER_IMBALANCE",
  CONCURRENT_CONFLICT: "CONCURRENT_CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type ErrorCode = keyof typeof ERROR_CODES;
